Directory=[PATH_DATA]##FileType=*.php##Find=/home/proceedings/www/htdocs/
Directory=[PATH_DATA]##FileType=*.def##Find=/home/proceedings/www/htdocs/
Directory=[PATH_DATA]##FileType=*.def##Find=/home/proceedings/www/bases/##Replace=[PATH_DATABASE]
Directory=[PATH_DATA]##FileType=*.def##Find=10.188.1.3:83##Replace=[SERVERNAME]
Directory=[PATH_DATA]xsl##FileType=*.xsl##Find=/home/proceedings/www/htdocs/
Directory=[PATH_DATA]iah##FileType=*.def##Find=/home/proceedings/www/cgi-bin/[PATH_CGI-BIN]
Directory=[PATH_DATA]iah##FileType=*.def##Find=/home/proceedings/www/bases/##Replace=[PATH_DATABASE]
Directory=[PATH_DATA]iah##FileType=*.def##Find=10.188.1.3:83##Replace=[SERVERNAME]
Directory=[PATH_CGI-BIN]iah-styles##FileType=place-sc.pft##Find=10.188.1.3:83##Replace=[SERVERNAME]
Directory=[PATH_CGI-BIN]iah-styles##FileType=place-sc.pft##Find=/home/proceedings/www/htdocs/
Directory=[PATH_CGI-BIN]iah-styles##FileType=lattes.xis##Find=/home/proceedings/www/bases/##Replace=[PATH_DATABASE]
Directory=[PATH_CGI-BIN]ScieloXML##FileType=redireciona.xis##Find=/home/proceedings/www/bases/##Replace=[PATH_DATABASE]
